# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'open-uri'

User.destroy_all
Product.destroy_all

# USER SEEDS
user1 = User.create!(first_name: 'testfirstname', last_name: 'testlastname', email: 'test123', password: 'test123')
# END User seeds

#MENS SHOE SEEDS
## Men's Tree Runner ##
mTreeRunnerblk = Product.create!(product_name: 'Tree Runners', size: 8, colorway: 'Jet Black', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our everyday sneaker made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/1-tree-runner-blk.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/2-tree-runner-blk.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/3-tree-runner-blk.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/4-tree-runner-blk.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/5-tree-runner-blk.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/6-tree-runner-blk.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/00-tree-runner-nvy.jpeg')
mTreeRunnerblk.photos.attach(io: file1, filename: '1-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file2, filename: '2-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file3, filename: '3-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file4, filename: '4-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file5, filename: '5-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file6, filename: '6-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file7, filename: '00-tree-runner-blk.jpeg')

mTreeRunnermist = Product.create!(product_name: 'Tree Runners', size: 8, colorway: 'Mist', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our everyday sneaker made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/1-tree-runner-mist.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/2-tree-runner-mist.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/3-tree-runner-mist.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/4-tree-runner-mist.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/5-tree-runner-mist.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/6-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file1, filename: '1-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file2, filename: '2-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file3, filename: '3-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file4, filename: '4-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file5, filename: '5-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file6, filename: '6-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file7, filename: '00-tree-runner-mist.jpeg')

mTreeRunnerkwhite = Product.create!(product_name: 'Tree Runners', size: 8, colorway: 'Kaikoura White', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our everyday sneaker made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/1-tree-runner-kwhite.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/2-tree-runner-kwhite.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/3-tree-runner-kwhite.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/4-tree-runner-kwhite.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/5-tree-runner-kwhite.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/6-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file1, filename: '1-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file2, filename: '2-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file3, filename: '3-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file4, filename: '4-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file5, filename: '5-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file6, filename: '6-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file7, filename: '00-tree-runner-kwhite.jpeg')

mTreeRunnernavyn = Product.create!(product_name: 'Tree Runners', size: 8, colorway: 'Navy Night', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our everyday sneaker made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/1-tree-runner-navyn.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/2-tree-runner-navyn.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/3-tree-runner-navyn.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/4-tree-runner-navyn.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/5-tree-runner-navyn.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/6-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file1, filename: '1-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file2, filename: '2-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file3, filename: '3-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file4, filename: '4-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file5, filename: '5-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file6, filename: '6-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file7, filename: '00-tree-runner-navyn.jpeg')


## Men's Tree Dasher ##
mTreeDasherqrt = Product.create!(product_name: 'Tree Dashers', size: 8, colorway: 'Quartz', gender: 'men', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/1-mtree-dasher-qrt.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/2-mtree-dasher.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/3-mtree-dasher-qrt.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/4-mtree-dasher-qrt.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/5-mtree-dasher-qrt.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/6-mtree-dasher-qrt.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/00-mtree-dasher-qrt.jpeg')
mTreeDasher.photos.attach(io: file1, filename: '1-mtree-dasher-qrt.jpeg')
mTreeDasher.photos.attach(io: file2, filename: '2-mtree-dasher-qrt.jpeg')
mTreeDasher.photos.attach(io: file3, filename: '3-mtree-dasher-qrt.jpeg')
mTreeDasher.photos.attach(io: file4, filename: '4-mtree-dasher-qrt.jpeg')
mTreeDasher.photos.attach(io: file5, filename: '5-mtree-dasher-qrt.jpeg')
mTreeDasher.photos.attach(io: file6, filename: '6-mtree-dasher-qrt.jpeg')
mTreeDasher.photos.attach(io: file7, filename: '00-mtree-dasher-qrt.jpeg')

mTreeDasherqrt = Product.create!(product_name: 'Tree Dashers', size: 8, colorway: 'Obsidian', gender: 'men', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/1-mtree-dasher-obsid.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/2-mtree-dasher-obsid.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/3-mtree-dasher-obsid.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/4-mtree-dasher-obsid.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/5-mtree-dasher-obsid.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/6-mtree-dasher-obsid.jpeg')
mTreeDasherqrt.photos.attach(io: file1, filename: '1-tree-dasher-obsid.jpeg')
mTreeDasherqrt.photos.attach(io: file2, filename: '2-tree-dasher-obsid.jpeg')
mTreeDasherqrt.photos.attach(io: file3, filename: '3-tree-dasher-obsid.jpeg')
mTreeDasherqrt.photos.attach(io: file4, filename: '4-tree-dasher-obsid.jpeg')
mTreeDasherqrt.photos.attach(io: file5, filename: '5-tree-dasher-obsid.jpeg')
mTreeDasherqrt.photos.attach(io: file6, filename: '6-tree-dasher-obsid.jpeg')
mTreeDasherqrt.photos.attach(io: file7, filename: '00-tree-dasher-qrt.jpeg')

mTreeDasherqrt = Product.create!(product_name: 'Tree Dashers', size: 8, colorway: 'Thunder', gender: 'men', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/1-mtree-dasher-thndr.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/2-mtree-dasher-thndr.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/3-mtree-dasher-thndr.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/4-mtree-dasher-thndr.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/5-mtree-dasher-thndr.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/6-mtree-dasher-thndr.jpeg')
mTreeDasherqrt.photos.attach(io: file1, filename: '1-tree-dasher-thndr.jpeg')
mTreeDasherqrt.photos.attach(io: file2, filename: '2-tree-dasher-thndr.jpeg')
mTreeDasherqrt.photos.attach(io: file3, filename: '3-tree-dasher-thndr.jpeg')
mTreeDasherqrt.photos.attach(io: file4, filename: '4-tree-dasher-thndr.jpeg')
mTreeDasherqrt.photos.attach(io: file5, filename: '5-tree-dasher-thndr.jpeg')
mTreeDasherqrt.photos.attach(io: file6, filename: '6-tree-dasher-thndr.jpeg')
mTreeDasherqrt.photos.attach(io: file7, filename: '00-tree-dasher-qrt.jpeg')

mTreeDasherqrt = Product.create!(product_name: 'Tree Dashers', size: 8, colorway: 'Diablo', gender: 'men', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/1-mtree-dasher-diablo.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/2-mtree-dasher-diablo.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/3-mtree-dasher-diablo.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/4-mtree-dasher-diablo.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/5-mtree-dasher-diablo.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/6-mtree-dasher-diablo.jpeg')
mTreeDasherqrt.photos.attach(io: file1, filename: '1-tree-dasher-diablo.jpeg')
mTreeDasherqrt.photos.attach(io: file2, filename: '2-tree-dasher-diablo.jpeg')
mTreeDasherqrt.photos.attach(io: file3, filename: '3-tree-dasher-diablo.jpeg')
mTreeDasherqrt.photos.attach(io: file4, filename: '4-tree-dasher-diablo.jpeg')
mTreeDasherqrt.photos.attach(io: file5, filename: '5-tree-dasher-diablo.jpeg')
mTreeDasherqrt.photos.attach(io: file6, filename: '6-tree-dasher-diablo.jpeg')
mTreeDasherqrt.photos.attach(io: file7, filename: '00-tree-dasher-qrt.jpeg')


## Men's Tree Topper ##
mTreeTopperchrc = Product.create!(product_name: 'Tree Toppers', size: 8, colorway: 'Charcoal', gender: 'men', price: 115, cart_id: [], review_id: [], detail1: "Our classic high top made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/1-tree-topper-chrc.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/2-tree-topper-chrc.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/3-tree-topper-chrc.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/4-tree-topper-chrc.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/5-tree-topper-chrc.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/6-tree-topper-chrc.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/00-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file1, filename: '1-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file2, filename: '2-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file3, filename: '3-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file4, filename: '4-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file5, filename: '5-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file6, filename: '6-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file7, filename: '00-tree-topper-chrc.jpeg')

mTreeTopperchalk = Product.create!(product_name: 'Tree Toppers', size: 8, colorway: 'Chalk', gender: 'men', price: 115, cart_id: [], review_id: [], detail1: "Our classic high top made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/1-tree-topper-chalk.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/2-tree-topper-chalk.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/3-tree-topper-chalk.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/4-tree-topper-chalk.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/5-tree-topper-chalk.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/6-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file1, filename: '1-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file2, filename: '2-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file3, filename: '3-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file4, filename: '4-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file5, filename: '5-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file6, filename: '6-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file7, filename: '00-tree-topper-chrc.jpeg')

mTreeTopperkjo = Product.create!(product_name: 'Tree Toppers', size: 8, colorway: 'Kauri Jo', gender: 'men', price: 115, cart_id: [], review_id: [], detail1: "Our classic high top made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/1-tree-topper-kjo.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/2-tree-topper-kjo.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/3-tree-topper-kjo.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/4-tree-topper-kjo.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/5-tree-topper-kjo.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/6-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file1, filename: '1-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file2, filename: '2-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file3, filename: '3-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file4, filename: '4-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file5, filename: '5-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file6, filename: '6-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file7, filename: '00-tree-topper-chrc.jpeg')

mTreeToppermarine = Product.create!(product_name: 'Tree Toppers', size: 8, colorway: 'Marine', gender: 'men', price: 115, cart_id: [], review_id: [], detail1: "Our classic high top made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/1-tree-topper-marine.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/2-tree-topper-marine.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/3-tree-topper-marine.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/4-tree-topper-marine.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/5-tree-topper-marine.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/6-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file1, filename: '1-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file2, filename: '2-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file3, filename: '3-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file4, filename: '4-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file5, filename: '5-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file6, filename: '6-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file7, filename: '00-tree-topper-chrc.jpeg')


## Men's Wool Runners ##
mWoolRunnernatgrey = Product.create!(product_name: 'Wool Runners', size: 8, colorway: 'Natural Grey', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our original everyday sneaker made with cozy merino wool.", detail2: "Soft Feel, Cozy Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/1-wool-runner-natgrey.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/2-wool-runner-natgrey.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/3-wool-runner-natgrey.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/4-wool-runner-natgrey.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/5-wool-runner-natgrey.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/6-wool-runner-natgrey.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/00-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file1, filename: '1-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file2, filename: '2-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file3, filename: '3-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file4, filename: '4-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file5, filename: '5-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file6, filename: '6-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file7, filename: '00-wool-runner-natgrey.jpeg')

mWoolRunnernatblack = Product.create!(product_name: 'Wool Runners', size: 8, colorway: 'Natural Black', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our original everyday sneaker made with cozy merino wool.", detail2: "Soft Feel, Cozy Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/1-wool-runner-natblk.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/2-wool-runner-natblk.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/3-wool-runner-natblk.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/4-wool-runner-natblk.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/5-wool-runner-natblk.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/6-wool-runner-natblk.jpeg')
mWoolRunnernatblack.photos.attach(io: file1, filename: '1-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file2, filename: '2-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file3, filename: '3-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file4, filename: '4-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file5, filename: '5-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file6, filename: '6-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file7, filename: '00-wool-runner-natgrey.jpeg')

mWoolRunnertukejo = Product.create!(product_name: 'Wool Runners', size: 8, colorway: 'Tuke Jo', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our original everyday sneaker made with cozy merino wool.", detail2: "Soft Feel, Cozy Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/1-wool-runner-tukjo.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/2-wool-runner-tukjo.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/3-wool-runner-tukjo.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/4-wool-runner-tukjo.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/5-wool-runner-tukjo.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/6-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file1, filename: '1-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file2, filename: '2-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file3, filename: '3-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file4, filename: '4-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file5, filename: '5-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file6, filename: '6-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file7, filename: '00-wool-runner-natgrey.jpeg')

mWoolRunnermist = Product.create!(product_name: 'Wool Runners', size: 8, colorway: 'Mist', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our original everyday sneaker made with cozy merino wool.", detail2: "Soft Feel, Cozy Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/1-wool-runner-mist.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/2-wool-runner-mist.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/3-wool-runner-mist.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/4-wool-runner-mist.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/5-wool-runner-mist.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/6-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file1, filename: '1-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file2, filename: '2-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file3, filename: '3-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file4, filename: '4-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file5, filename: '5-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file6, filename: '6-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file7, filename: '00-wool-runner-natgrey.jpeg')
# END Mens shoe seeds



# WOMENS SHOE SEEDS

## Women's Tree Piper ##
wTreePiper = Product.create!(product_name: 'Tree Piper', size: 5, colorway: 'Luna', gender: 'women', price: 95, cart_id: [], review_id: [], detail1: "Our low top sneaker, made with light and breezy eucalyptus tree fiber.", detail2: "All-Day Comfort. Everyday Style")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/1-tree-piper-lna.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/2-tree-piper-lna.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/3-tree-piper-lna.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/4-tree-piper-lna.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/5-tree-piper-lna.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/6-tree-piper-lna.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/00-tree-piper-lna.jpeg')
wTreePiper.photos.attach(io: file1, filename: '1-tree-piper-lna.jpeg')
wTreePiper.photos.attach(io: file2, filename: '2-tree-piper-lna.jpeg')
wTreePiper.photos.attach(io: file3, filename: '3-tree-piper-lna.jpeg')
wTreePiper.photos.attach(io: file4, filename: '4-tree-piper-lna.jpeg')
wTreePiper.photos.attach(io: file5, filename: '5-tree-piper-lna.jpeg')
wTreePiper.photos.attach(io: file6, filename: '6-tree-piper-lna.jpeg')
wTreePiper.photos.attach(io: file7, filename: '00-tree-piper-lna.jpeg')












### SAMPLE
# mTreeDasherqrt = Product.create!(product_name: 'Tree Dasher', size: 8, colorway: 'Obsidian', gender: 'men', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
# file1 = URI.open('')
# file2 = URI.open('')
# file3 = URI.open('')
# file4 = URI.open('')
# file5 = URI.open('')
# file6 = URI.open('')
# mTreeDasher.photos.attach(io: file1, filename: '')
# mTreeDasher.photos.attach(io: file2, filename: '')
# mTreeDasher.photos.attach(io: file3, filename: '')
# mTreeDasher.photos.attach(io: file4, filename: '')
# mTreeDasher.photos.attach(io: file5, filename: '')
# mTreeDasher.photos.attach(io: file6, filename: '')
# mTreeDasher.photos.attach(io: file7, filename: '')