# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'open-uri'

User.destroy_all
Product.destroy_all
Review.destroy_all
Cart.destroy_all

# USER SEEDS
user1 = User.create!(first_name: 'testfirstname', last_name: 'testlastname', email: 'test123', password: 'test123')
user2 = User.create!(first_name: 'Demo', last_name: 'User', email: 'DemoUser@demo.com', password: 'test123')
# END User seeds


#MENS SHOE SEEDS
## Men's Tree Dasher ##
mTreeDasherqrt = Product.create!(display: true, product_name: 'Tree Dashers', size: 8, colorway: 'Quartz', gender: 'men', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/1-mtree-dasher-qrt.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/2-mtree-dasher.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/3-mtree-dasher-qrt.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/4-mtree-dasher-qrt.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/5-mtree-dasher-qrt.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/6-mtree-dasher-qrt.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/00-mtree-dasher-qrt.jpeg')
mTreeDasherqrt.photos.attach(io: file1, filename: '1-mtree-dasher-qrt.jpeg')
mTreeDasherqrt.photos.attach(io: file2, filename: '2-mtree-dasher-qrt.jpeg')
mTreeDasherqrt.photos.attach(io: file3, filename: '3-mtree-dasher-qrt.jpeg')
mTreeDasherqrt.photos.attach(io: file4, filename: '4-mtree-dasher-qrt.jpeg')
mTreeDasherqrt.photos.attach(io: file5, filename: '5-mtree-dasher-qrt.jpeg')
mTreeDasherqrt.photos.attach(io: file6, filename: '6-mtree-dasher-qrt.jpeg')
mTreeDasherqrt.photos.attach(io: file7, filename: '00-mtree-dasher-qrt.jpeg')

mTreeDasherobsid = Product.create!(display: true, product_name: 'Tree Dashers', size: 8, colorway: 'Obsidian', gender: 'men', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/1-mtree-dasher-obsid.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/2-mtree-dasher-obsid.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/3-mtree-dasher-obsid.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/4-mtree-dasher-obsid.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/5-mtree-dasher-obsid.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/6-mtree-dasher-obsid.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/00-mtree-dasher-qrt.jpeg')
mTreeDasherobsid.photos.attach(io: file1, filename: '1-tree-dasher-obsid.jpeg')
mTreeDasherobsid.photos.attach(io: file2, filename: '2-tree-dasher-obsid.jpeg')
mTreeDasherobsid.photos.attach(io: file3, filename: '3-tree-dasher-obsid.jpeg')
mTreeDasherobsid.photos.attach(io: file4, filename: '4-tree-dasher-obsid.jpeg')
mTreeDasherobsid.photos.attach(io: file5, filename: '5-tree-dasher-obsid.jpeg')
mTreeDasherobsid.photos.attach(io: file6, filename: '6-tree-dasher-obsid.jpeg')
mTreeDasherobsid.photos.attach(io: file7, filename: '00-tree-dasher-qrt.jpeg')

mTreeDasherthundr = Product.create!(display: true, product_name: 'Tree Dashers', size: 8, colorway: 'Thunder', gender: 'men', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/1-mtree-dasher-thndr.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/2-mtree-dasher-thndr.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/3-mtree-dasher-thndr.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/4-mtree-dasher-thndr.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/5-mtree-dasher-thndr.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/6-mtree-dasher-thndr.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/00-mtree-dasher-qrt.jpeg')
mTreeDasherthundr.photos.attach(io: file1, filename: '1-tree-dasher-thndr.jpeg')
mTreeDasherthundr.photos.attach(io: file2, filename: '2-tree-dasher-thndr.jpeg')
mTreeDasherthundr.photos.attach(io: file3, filename: '3-tree-dasher-thndr.jpeg')
mTreeDasherthundr.photos.attach(io: file4, filename: '4-tree-dasher-thndr.jpeg')
mTreeDasherthundr.photos.attach(io: file5, filename: '5-tree-dasher-thndr.jpeg')
mTreeDasherthundr.photos.attach(io: file6, filename: '6-tree-dasher-thndr.jpeg')
mTreeDasherthundr.photos.attach(io: file7, filename: '00-tree-dasher-qrt.jpeg')

mTreeDasherdiable = Product.create!(display: true, product_name: 'Tree Dashers', size: 8, colorway: 'Diablo', gender: 'men', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/1-mtree-dasher-diablo.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/2-mtree-dasher-diablo.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/3-mtree-dasher-diablo.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/4-mtree-dasher-diablo.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/5-mtree-dasher-diablo.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/6-mtree-dasher-diablo.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_dasher/00-mtree-dasher-qrt.jpeg')
mTreeDasherdiable.photos.attach(io: file1, filename: '1-tree-dasher-diablo.jpeg')
mTreeDasherdiable.photos.attach(io: file2, filename: '2-tree-dasher-diablo.jpeg')
mTreeDasherdiable.photos.attach(io: file3, filename: '3-tree-dasher-diablo.jpeg')
mTreeDasherdiable.photos.attach(io: file4, filename: '4-tree-dasher-diablo.jpeg')
mTreeDasherdiable.photos.attach(io: file5, filename: '5-tree-dasher-diablo.jpeg')
mTreeDasherdiable.photos.attach(io: file6, filename: '6-tree-dasher-diablo.jpeg')
mTreeDasherdiable.photos.attach(io: file7, filename: '00-tree-dasher-qrt.jpeg')


## Men's Tree Runner ##
mTreeRunnerblk = Product.create!(display: true, product_name: 'Tree Runners', size: 8, colorway: 'Jet Black', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our everyday sneaker made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/1-tree-runner-blk.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/2-tree-runner-blk.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/3-tree-runner-blk.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/4-tree-runner-blk.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/5-tree-runner-blk.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/6-tree-runner-blk.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/00-tree-runner-nvy.jpeg')
mTreeRunnerblk.photos.attach(io: file1, filename: '1-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file2, filename: '2-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file3, filename: '3-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file4, filename: '4-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file5, filename: '5-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file6, filename: '6-tree-runner-blk.jpeg')
mTreeRunnerblk.photos.attach(io: file7, filename: '00-tree-runner-nvy.jpeg')

mTreeRunnermist = Product.create!(display: true, product_name: 'Tree Runners', size: 8, colorway: 'Mist', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our everyday sneaker made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/1-tree-runner-mist.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/2-tree-runner-mist.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/3-tree-runner-mist.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/4-tree-runner-mist.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/5-tree-runner-mist.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/6-tree-runner-mist.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/00-tree-runner-nvy.jpeg')
mTreeRunnermist.photos.attach(io: file1, filename: '1-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file2, filename: '2-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file3, filename: '3-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file4, filename: '4-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file5, filename: '5-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file6, filename: '6-tree-runner-mist.jpeg')
mTreeRunnermist.photos.attach(io: file7, filename: '00-tree-runner-nvy.jpeg')

mTreeRunnerkwhite = Product.create!(display: true, product_name: 'Tree Runners', size: 8, colorway: 'Kaikoura White', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our everyday sneaker made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/1-tree-runner-kwhite.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/2-tree-runner-kwhite.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/3-tree-runner-kwhite.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/4-tree-runner-kwhite.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/5-tree-runner-kwhite.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/6-tree-runner-kwhite.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/00-tree-runner-nvy.jpeg')
mTreeRunnerkwhite.photos.attach(io: file1, filename: '1-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file2, filename: '2-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file3, filename: '3-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file4, filename: '4-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file5, filename: '5-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file6, filename: '6-tree-runner-kwhite.jpeg')
mTreeRunnerkwhite.photos.attach(io: file7, filename: '00-tree-runner-nvy.jpeg')

mTreeRunnernavyn = Product.create!(display: true, product_name: 'Tree Runners', size: 8, colorway: 'Navy Night', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our everyday sneaker made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/1-tree-runner-navyn.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/2-tree-runner-navyn.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/3-tree-runner-navyn.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/4-tree-runner-navyn.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/5-tree-runner-navyn.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/6-tree-runner-navyn.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_runner/00-tree-runner-nvy.jpeg')
mTreeRunnernavyn.photos.attach(io: file1, filename: '1-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file2, filename: '2-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file3, filename: '3-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file4, filename: '4-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file5, filename: '5-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file6, filename: '6-tree-runner-navyn.jpeg')
mTreeRunnernavyn.photos.attach(io: file7, filename: '00-tree-runner-nvy.jpeg')


## Men's Tree Topper ##
mTreeTopperchrc = Product.create!(display: true, product_name: 'Tree Toppers', size: 8, colorway: 'Charcoal', gender: 'men', price: 115, cart_id: [], review_id: [], detail1: "Our classic high top made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/1-tree-topper-chrc.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/2-tree-topper-chrc.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/3-tree-topper-chrc.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/4-tree-topper-chrc.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/5-tree-topper-chrc.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/6-tree-topper-chrc.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/00-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file1, filename: '1-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file2, filename: '2-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file3, filename: '3-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file4, filename: '4-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file5, filename: '5-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file6, filename: '6-tree-topper-chrc.jpeg')
mTreeTopperchrc.photos.attach(io: file7, filename: '00-tree-topper-chrc.jpeg')

mTreeTopperchalk = Product.create!(display: true, product_name: 'Tree Toppers', size: 8, colorway: 'Chalk', gender: 'men', price: 115, cart_id: [], review_id: [], detail1: "Our classic high top made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/1-tree-topper-chalk.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/2-tree-topper-chalk.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/3-tree-topper-chalk.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/4-tree-topper-chalk.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/5-tree-topper-chalk.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/6-tree-topper-chalk.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/00-tree-topper-chrc.jpeg')
mTreeTopperchalk.photos.attach(io: file1, filename: '1-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file2, filename: '2-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file3, filename: '3-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file4, filename: '4-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file5, filename: '5-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file6, filename: '6-tree-topper-chalk.jpeg')
mTreeTopperchalk.photos.attach(io: file7, filename: '00-tree-topper-chrc.jpeg')

mTreeTopperkjo = Product.create!(display: true, product_name: 'Tree Toppers', size: 8, colorway: 'Kauri Jo', gender: 'men', price: 115, cart_id: [], review_id: [], detail1: "Our classic high top made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/1-tree-topper-kjo.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/2-tree-topper-kjo.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/3-tree-topper-kjo.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/4-tree-topper-kjo.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/5-tree-topper-kjo.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/6-tree-topper-kjo.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/00-tree-topper-chrc.jpeg')
mTreeTopperkjo.photos.attach(io: file1, filename: '1-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file2, filename: '2-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file3, filename: '3-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file4, filename: '4-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file5, filename: '5-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file6, filename: '6-tree-topper-kjo.jpeg')
mTreeTopperkjo.photos.attach(io: file7, filename: '00-tree-topper-chrc.jpeg')

mTreeToppermarine = Product.create!(display: true, product_name: 'Tree Toppers', size: 8, colorway: 'Marine', gender: 'men', price: 115, cart_id: [], review_id: [], detail1: "Our classic high top made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/1-tree-topper-marine.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/2-tree-topper-marine.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/3-tree-topper-marine.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/4-tree-topper-marine.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/5-tree-topper-marine.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/6-tree-topper-marine.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mtree_topper/00-tree-topper-chrc.jpeg')
mTreeToppermarine.photos.attach(io: file1, filename: '1-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file2, filename: '2-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file3, filename: '3-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file4, filename: '4-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file5, filename: '5-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file6, filename: '6-tree-topper-marine.jpeg')
mTreeToppermarine.photos.attach(io: file7, filename: '00-tree-topper-chrc.jpeg')


## Men's Wool Runners ##
mWoolRunnernatgrey = Product.create!(display: true, product_name: 'Wool Runners', size: 8, colorway: 'Natural Grey', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our original everyday sneaker made with cozy merino wool.", detail2: "Soft Feel, Cozy Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/1-wool-runner-natgrey.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/2-wool-runner-natgrey.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/3-wool-runner-natgrey.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/4-wool-runner-natgrey.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/5-wool-runner-natgrey.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/6-wool-runner-natgrey.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/00-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file1, filename: '1-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file2, filename: '2-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file3, filename: '3-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file4, filename: '4-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file5, filename: '5-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file6, filename: '6-wool-runner-natgrey.jpeg')
mWoolRunnernatgrey.photos.attach(io: file7, filename: '00-wool-runner-natgrey.jpeg')

mWoolRunnernatblack = Product.create!(display: true, product_name: 'Wool Runners', size: 8, colorway: 'Natural Black', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our original everyday sneaker made with cozy merino wool.", detail2: "Soft Feel, Cozy Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/1-wool-runner-natblk.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/2-wool-runner-natblk.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/3-wool-runner-natblk.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/4-wool-runner-natblk.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/5-wool-runner-natblk.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/6-wool-runner-natblk.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/00-wool-runner-natgrey.jpeg')
mWoolRunnernatblack.photos.attach(io: file1, filename: '1-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file2, filename: '2-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file3, filename: '3-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file4, filename: '4-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file5, filename: '5-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file6, filename: '6-wool-runner-natblk')
mWoolRunnernatblack.photos.attach(io: file7, filename: '00-wool-runner-natgrey.jpeg')

mWoolRunnertukejo = Product.create!(display: true, product_name: 'Wool Runners', size: 8, colorway: 'Tuke Jo', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our original everyday sneaker made with cozy merino wool.", detail2: "Soft Feel, Cozy Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/1-wool-runner-tukjo.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/2-wool-runner-tukjo.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/3-wool-runner-tukjo.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/4-wool-runner-tukjo.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/5-wool-runner-tukjo.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/6-wool-runner-tukjo.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/00-wool-runner-natgrey.jpeg')
mWoolRunnertukejo.photos.attach(io: file1, filename: '1-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file2, filename: '2-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file3, filename: '3-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file4, filename: '4-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file5, filename: '5-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file6, filename: '6-wool-runner-tukjo.jpeg')
mWoolRunnertukejo.photos.attach(io: file7, filename: '00-wool-runner-natgrey.jpeg')

mWoolRunnermist = Product.create!(display: true, product_name: 'Wool Runners', size: 8, colorway: 'Mist', gender: 'men', price: 95, cart_id: [], review_id: [], detail1: "Our original everyday sneaker made with cozy merino wool.", detail2: "Soft Feel, Cozy Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/1-wool-runner-mist.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/2-wool-runner-mist.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/3-wool-runner-mist.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/4-wool-runner-mist.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/5-wool-runner-mist.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/6-wool-runner-mist.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/mwool_runner/00-wool-runner-natgrey.jpeg')
mWoolRunnermist.photos.attach(io: file1, filename: '1-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file2, filename: '2-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file3, filename: '3-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file4, filename: '4-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file5, filename: '5-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file6, filename: '6-wool-runner-mist.jpeg')
mWoolRunnermist.photos.attach(io: file7, filename: '00-wool-runner-natgrey.jpeg')
# END Mens shoe seeds



# WOMENS SHOE SEEDS

## Women's Tree Piper ##
wTreePiperluna = Product.create!(display: true, product_name: 'Tree Pipers', size: 5, colorway: 'Luna', gender: 'women', price: 95, cart_id: [], review_id: [], detail1: "Our low top sneaker, made with light and breezy eucalyptus tree fiber.", detail2: "All-Day Comfort. Everyday Style")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/1-tree-piper-lna.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/2-tree-piper-lna.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/3-tree-piper-lna.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/4-tree-piper-lna.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/5-tree-piper-lna.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/6-tree-piper-lna.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/00-tree-piper-lna.jpeg')
wTreePiperluna.photos.attach(io: file1, filename: '1-tree-piper-lna.jpeg')
wTreePiperluna.photos.attach(io: file2, filename: '2-tree-piper-lna.jpeg')
wTreePiperluna.photos.attach(io: file3, filename: '3-tree-piper-lna.jpeg')
wTreePiperluna.photos.attach(io: file4, filename: '4-tree-piper-lna.jpeg')
wTreePiperluna.photos.attach(io: file5, filename: '5-tree-piper-lna.jpeg')
wTreePiperluna.photos.attach(io: file6, filename: '6-tree-piper-lna.jpeg')
wTreePiperluna.photos.attach(io: file7, filename: '00-tree-piper-lna.jpeg')

wTreePiperkwhite = Product.create!(display: true, product_name: 'Tree Pipers', size: 5, colorway: 'Kaikoura White', gender: 'women', price: 95, cart_id: [], review_id: [], detail1: "Our low top sneaker, made with light and breezy eucalyptus tree fiber.", detail2: "All-Day Comfort. Everyday Style")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/1-tree-piper-kwhite.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/2-tree-piper-kwhite.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/3-tree-piper-kwhite.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/4-tree-piper-kwhite.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/5-tree-piper-kwhite.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/6-tree-piper-kwhite.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/00-tree-piper-lna.jpeg')
wTreePiperkwhite.photos.attach(io: file1, filename: '1-tree-piper-kwhite.jpeg')
wTreePiperkwhite.photos.attach(io: file2, filename: '2-tree-piper-kwhite.jpeg')
wTreePiperkwhite.photos.attach(io: file3, filename: '3-tree-piper-kwhite.jpeg')
wTreePiperkwhite.photos.attach(io: file4, filename: '4-tree-piper-kwhite.jpeg')
wTreePiperkwhite.photos.attach(io: file5, filename: '5-tree-piper-kwhite.jpeg')
wTreePiperkwhite.photos.attach(io: file6, filename: '6-tree-piper-kwhite.jpeg')
wTreePiperkwhite.photos.attach(io: file7, filename: '00-tree-piper-lna.jpeg')

wTreePipermoonrise = Product.create!(display: true, product_name: 'Tree Pipers', size: 5, colorway: 'Moonrise', gender: 'women', price: 95, cart_id: [], review_id: [], detail1: "Our low top sneaker, made with light and breezy eucalyptus tree fiber.", detail2: "All-Day Comfort. Everyday Style")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/1-tree-piper-moonrise.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/2-tree-piper-moonrise.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/3-tree-piper-moonrise.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/4-tree-piper-moonrise.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/5-tree-piper-moonrise.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/00-tree-piper-lna.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/6-tree-piper-moonrise.jpeg')
wTreePipermoonrise.photos.attach(io: file1, filename: '1-tree-piper-moonrise.jpeg')
wTreePipermoonrise.photos.attach(io: file2, filename: '2-tree-piper-moonrise.jpeg')
wTreePipermoonrise.photos.attach(io: file3, filename: '3-tree-piper-moonrise.jpeg')
wTreePipermoonrise.photos.attach(io: file4, filename: '4-tree-piper-moonrise.jpeg')
wTreePipermoonrise.photos.attach(io: file5, filename: '5-tree-piper-moonrise.jpeg')
wTreePipermoonrise.photos.attach(io: file6, filename: '6-tree-piper-moonrise.jpeg')
wTreePipermoonrise.photos.attach(io: file7, filename: '00-tree-piper-lna.jpeg')

wTreePipermulberry = Product.create!(display: true, product_name: 'Tree Pipers', size: 5, colorway: 'Mulberry', gender: 'women', price: 95, cart_id: [], review_id: [], detail1: "Our low top sneaker, made with light and breezy eucalyptus tree fiber.", detail2: "All-Day Comfort. Everyday Style")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/1-tree-piper-mulberry.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/2-tree-piper-mulberry.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/3-tree-piper-mulberry.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/4-tree-piper-mulberry.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/5-tree-piper-mulberry.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/6-tree-piper-mulberry.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_piper/00-tree-piper-lna.jpeg')
wTreePipermulberry.photos.attach(io: file1, filename: '1-tree-piper-lna.jpeg')
wTreePipermulberry.photos.attach(io: file2, filename: '2-tree-piper-lna.jpeg')
wTreePipermulberry.photos.attach(io: file3, filename: '3-tree-piper-lna.jpeg')
wTreePipermulberry.photos.attach(io: file4, filename: '4-tree-piper-lna.jpeg')
wTreePipermulberry.photos.attach(io: file5, filename: '5-tree-piper-lna.jpeg')
wTreePipermulberry.photos.attach(io: file6, filename: '6-tree-piper-lna.jpeg')
wTreePipermulberry.photos.attach(io: file7, filename: '00-tree-piper-lna.jpeg')
## end product 1


## Produ here!!
wTreeDashergeyser = Product.create!(display: true, product_name: 'Tree Dashers', size: 5, colorway: 'Geyser', gender: 'women', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/1-wtree-dasher.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/2-wtree-dasher.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/3-wtree-dasher.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/4-wtree-dasher.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/5-wtree-dasher.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/6-wtree-dasher-geyser.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/00-wtree-dasher.webp')
wTreeDashergeyser.photos.attach(io: file1, filename: '1-tree-dasher-geyser.jpeg')
wTreeDashergeyser.photos.attach(io: file2, filename: '2-tree-dasher-geyser.jpeg')
wTreeDashergeyser.photos.attach(io: file3, filename: '3-tree-dasher-geyser.jpeg')
wTreeDashergeyser.photos.attach(io: file4, filename: '4-tree-dasher-geyser.jpeg')
wTreeDashergeyser.photos.attach(io: file5, filename: '5-tree-dasher-geyser.jpeg')
wTreeDashergeyser.photos.attach(io: file6, filename: '6-tree-dasher-geyser.jpeg')
wTreeDashergeyser.photos.attach(io: file7, filename: '00-tree-dasher.webp')

wTreeDashercyclone = Product.create!(display: true, product_name: 'Tree Dashers', size: 5, colorway: 'Cyclone', gender: 'women', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/1-wtree-cyclone.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/2-wtree-cyclone.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/3-wtree-cyclone.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/4-wtree-cyclone.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/5-wtree-cyclone.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/6-wtree-cyclone.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/00-wtree-dasher.webp')
wTreeDashercyclone.photos.attach(io: file1, filename: '1-tree-dasher-cyclone.jpeg')
wTreeDashercyclone.photos.attach(io: file2, filename: '2-tree-dasher-cyclone.jpeg')
wTreeDashercyclone.photos.attach(io: file3, filename: '3-tree-dasher-cyclone.jpeg')
wTreeDashercyclone.photos.attach(io: file4, filename: '4-tree-dasher-cyclone.jpeg')
wTreeDashercyclone.photos.attach(io: file5, filename: '5-tree-dasher-cyclone.jpeg')
wTreeDashercyclone.photos.attach(io: file6, filename: '6-tree-dasher-cyclone.jpeg')
wTreeDashercyclone.photos.attach(io: file7, filename: '00-tree-dasher.webp')

wTreeDasherobsidian = Product.create!(display: true, product_name: 'Tree Dashers', size: 5, colorway: 'Obsidian', gender: 'women', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/1-wtree-obsidian.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/2-wtree-obsidian.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/3-wtree-obsidian.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/4-wtree-obsidian.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/5-wtree-obsidian.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/6-wtree-obsidian.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/00-wtree-dasher.webp')
wTreeDasherobsidian.photos.attach(io: file1, filename: '1-tree-dashers-obsidian.jpeg')
wTreeDasherobsidian.photos.attach(io: file2, filename: '2-tree-dashers-obsidian.jpeg')
wTreeDasherobsidian.photos.attach(io: file3, filename: '3-tree-dashers-obsidian.jpeg')
wTreeDasherobsidian.photos.attach(io: file4, filename: '4-tree-dashers-obsidian.jpeg')
wTreeDasherobsidian.photos.attach(io: file5, filename: '5-tree-dashers-obsidian.jpeg')
wTreeDasherobsidian.photos.attach(io: file6, filename: '6-tree-dashers-obsidian.jpeg')
wTreeDasherobsidian.photos.attach(io: file7, filename: '00-tree-dasher.webp')

wTreeDashermirage = Product.create!(display: true, product_name: 'Tree Dashers', size: 5, colorway: 'Mirage', gender: 'women', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/1-wtree-mirage.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/2-wtree-mirage.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/3-wtree-mirage.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/4-wtree-mirage.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/5-wtree-mirage.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/6-wtree-mirage.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_dasher/00-wtree-dasher.webp')
wTreeDashermirage.photos.attach(io: file1, filename: '1-tree-dashers-mirage.jpeg')
wTreeDashermirage.photos.attach(io: file2, filename: '2-tree-dashers-mirage.jpeg')
wTreeDashermirage.photos.attach(io: file3, filename: '3-tree-dashers-mirage.jpeg')
wTreeDashermirage.photos.attach(io: file4, filename: '4-tree-dashers-mirage.jpeg')
wTreeDashermirage.photos.attach(io: file5, filename: '5-tree-dashers-mirage.jpeg')
wTreeDashermirage.photos.attach(io: file6, filename: '6-tree-dashers-mirage.jpeg')
wTreeDashermirage.photos.attach(io: file7, filename: '00-tree-dasher.webp')




## Produ here!!
 wTreeLoungermist = Product.create!(display: true, product_name: 'Tree Loungers', size: 5, colorway: 'Mist', gender: 'women', price: 95, cart_id: [], review_id: [], detail1: "Our casual slip-on made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/1-tree-lounger-mist.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/2-tree-lounger-mist.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/3-tree-lounger-mist.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/4-tree-lounger-mist.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/5-tree-lounger-mist.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/6-tree-lounger-mist.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/00-tree-lounger.webp')
wTreeLoungermist.photos.attach(io: file1, filename: '1-tree-lounger-mist.jpeg')
wTreeLoungermist.photos.attach(io: file2, filename: '2-tree-lounger-mist.jpeg')
wTreeLoungermist.photos.attach(io: file3, filename: '3-tree-lounger-mist.jpeg')
wTreeLoungermist.photos.attach(io: file4, filename: '4-tree-lounger-mist.jpeg')
wTreeLoungermist.photos.attach(io: file5, filename: '5-tree-lounger-mist.jpeg')
wTreeLoungermist.photos.attach(io: file6, filename: '6-tree-lounger-mist.jpeg')
wTreeLoungermist.photos.attach(io: file7, filename: '00-tree-lounger.webp')

wTreeLoungernnight= Product.create!(display: true, product_name: 'Tree Loungers', size: 5, colorway: 'Navy Night', gender: 'women', price: 95, cart_id: [], review_id: [], detail1: "Our casual slip-on made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/1-tree-lounger-nnight.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/2-tree-lounger-nnight.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/3-tree-lounger-nnight.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/4-tree-lounger-nnight.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/5-tree-lounger-nnight.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/6-tree-lounger-nnight.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/00-tree-lounger.webp')
wTreeLoungernnight.photos.attach(io: file1, filename: '1-tree-lounger-nnight.jpeg')
wTreeLoungernnight.photos.attach(io: file2, filename: '2-tree-lounger-nnight.jpeg')
wTreeLoungernnight.photos.attach(io: file3, filename: '3-tree-lounger-nnight.jpeg')
wTreeLoungernnight.photos.attach(io: file4, filename: '4-tree-lounger-nnight.jpeg')
wTreeLoungernnight.photos.attach(io: file5, filename: '5-tree-lounger-nnight.jpeg')
wTreeLoungernnight.photos.attach(io: file6, filename: '6-tree-lounger-nnight.jpeg')
wTreeLoungernnight.photos.attach(io: file7, filename: '00-tree-lounger.webp')

wTreeLoungerkwhite = Product.create!(display: true, product_name: 'Tree Loungers', size: 5, colorway: 'Kaikoura White', gender: 'women', price: 95, cart_id: [], review_id: [], detail1: "Our casual slip-on made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/1-tree-lounger-kwhite.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/2-tree-lounger-kwhite.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/3-tree-lounger-kwhite.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/4-tree-lounger-kwhite.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/5-tree-lounger-kwhite.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/6-tree-lounger-kwhite.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/00-tree-lounger.webp')
wTreeLoungerkwhite.photos.attach(io: file1, filename: '1-tree-lounger-kwhite.jpeg')
wTreeLoungerkwhite.photos.attach(io: file2, filename: '2-tree-lounger-kwhite.jpeg')
wTreeLoungerkwhite.photos.attach(io: file3, filename: '3-tree-lounger-kwhite.jpeg')
wTreeLoungerkwhite.photos.attach(io: file4, filename: '4-tree-lounger-kwhite.jpeg')
wTreeLoungerkwhite.photos.attach(io: file5, filename: '5-tree-lounger-kwhite.jpeg')
wTreeLoungerkwhite.photos.attach(io: file6, filename: '6-tree-lounger-kwhite.jpeg')
wTreeLoungerkwhite.photos.attach(io: file7, filename: '00-tree-lounger.webp')
 
wTreeLoungerluna = Product.create!(display: true, product_name: 'Tree Loungers', size: 5, colorway: 'Luna', gender: 'women', price: 95, cart_id: [], review_id: [], detail1: "Our casual slip-on made with breezy eucalyptus tree.", detail2: "Breezy Feel, Light Material")
file1 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/1-tree-lounger-luna.jpeg')
file2 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/2-tree-lounger-luna.jpeg')
file3 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/3-tree-lounger-luna.jpeg')
file4 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/4-tree-lounger-luna.jpeg')
file5 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/5-tree-lounger-luna.jpeg')
file6 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/6-tree-lounger-luna.jpeg')
file7 = URI.open('https://birdwell-dev.s3.us-west-1.amazonaws.com/wtree_lounger/00-tree-lounger.webp')
wTreeLoungerluna.photos.attach(io: file1, filename: '1-tree-lounger-luna.jpeg')
wTreeLoungerluna.photos.attach(io: file2, filename: '2-tree-lounger-luna.jpeg')
wTreeLoungerluna.photos.attach(io: file3, filename: '3-tree-lounger-luna.jpeg')
wTreeLoungerluna.photos.attach(io: file4, filename: '4-tree-lounger-luna.jpeg')
wTreeLoungerluna.photos.attach(io: file5, filename: '5-tree-lounger-luna.jpeg')
wTreeLoungerluna.photos.attach(io: file6, filename: '6-tree-lounger-luna.jpeg')
wTreeLoungerluna.photos.attach(io: file7, filename: '00-tree-lounger.webp')


### SAMPLE
# mTreeDasherqrt = Product.create!(product_name: 'Tree Dasher', size: 8, colorway: 'Obsidian', gender: 'men', price: 125, cart_id: [], review_id: [], detail1: "Our running shoe designed with breathable Tree material.", detail2: "Supportive Design, Daily Run")
# file1 = URI.open('')
# file2 = URI.open('')
# file3 = URI.open('')
# file4 = URI.open('')
# file5 = URI.open('')
# file6 = URI.open('')
# mTreeDasher.photos.attach(io: file1, filename: '')
# mTreeDasher.photos.attach(io: file2, filename: '')
# mTreeDasher.photos.attach(io: file3, filename: '')
# mTreeDasher.photos.attach(io: file4, filename: '')
# mTreeDasher.photos.attach(io: file5, filename: '')
# mTreeDasher.photos.attach(io: file6, filename: '')
# mTreeDasher.photos.attach(io: file7, filename: '')